// layout.js (or layout.jsx)
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
// Note: next/font/google is a Next.js specific feature.
// If you're not in a Next.js project, you'd need to handle fonts differently.
import { Outfit} from 'next/font/google';
import './globals.css';
import Provider from "./provider";


const outfit= Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
});

// `Metadata` type annotation is removed as it's TypeScript-specific.
export const metadata = {
  title: 'Scholar 101',
  description: 'Generated by create next app',
};

// Type annotation for `children` is removed.
export default function RootLayout({ children }) {
  return (
      <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={outfit.className}>
          
    <Provider>
      {children}

    </Provider>
          
        </body>
      </html>
    </ClerkProvider>
  );
  
}
console.log("Provider")
console.log('Publishable Key:', process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)
